apiVersion: v1
kind: Service
metadata:
  name: k8s-scw
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: k8s-scw
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-scw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-scw
  template:
    metadata:
      labels:
        app: k8s-scw
    spec:
      containers:
        - name: web
          image: shubcodes/k8s_scaleway
          ports:
            - name: http
              containerPort: 80
